<script>
  import { onMount } from 'svelte';

  let customModels = [];
  let showModal = false;
  let currentModel = null; // For editing or adding
  let isEditing = false;

  // Form fields
  let modelId = '';
  let modelName = '';
  let description = '';
  let provider = 'openai'; // Default provider
  let baseUrl = '';
  let apiKeyEnvVar = '';
  let maxTokens = 4096;
  let maxOutputTokens = 1024;
  let preferredModelOutputFormat = 'xml'; // Default
  let defaultMaxConvoTokens = 2000;


  async function fetchCustomModels() {
    try {
      const response = await fetch('/api/ui/custom-models');
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      customModels = await response.json();
      if (!customModels) customModels = []; // Ensure it's an array
    } catch (error) {
      console.error("Failed to fetch custom models:", error);
      customModels = []; // Fallback to empty array on error
    }
  }

  onMount(fetchCustomModels);

  function openAddModal() {
    isEditing = false;
    currentModel = null;
    // Reset form fields
    modelId = '';
    modelName = '';
    description = '';
    provider = 'openai';
    baseUrl = '';
    apiKeyEnvVar = '';
    maxTokens = 4096;
    maxOutputTokens = 1024;
    preferredModelOutputFormat = 'xml';
    defaultMaxConvoTokens = 2000;

    showModal = true;
  }

  function openEditModal(model) {
    isEditing = true;
    currentModel = model;
    // Populate form fields
    modelId = model.modelId || '';
    modelName = model.modelName || '';
    description = model.description || '';
    provider = model.provider || 'openai';
    baseUrl = model.baseUrl || '';
    apiKeyEnvVar = model.apiKeyEnvVar || '';
    maxTokens = model.maxTokens || 4096;
    maxOutputTokens = model.maxOutputTokens || 1024;
    preferredModelOutputFormat = model.preferredModelOutputFormat || 'xml';
    defaultMaxConvoTokens = model.defaultMaxConvoTokens || 2000;
    showModal = true;
  }

  function closeModal() {
    showModal = false;
    currentModel = null;
  }

  async function handleSubmit() {
    const modelData = {
      modelId: modelId, // This is the "name" field in AvailableModel's BaseModelConfig
      modelName: modelName, // This is the "modelId" field in AvailableModel's BaseModelConfig
      description: description,
      provider: provider,
      baseUrl: baseUrl,
      apiKeyEnvVar: apiKeyEnvVar,
      maxTokens: parseInt(maxTokens, 10),
      maxOutputTokens: parseInt(maxOutputTokens, 10),
      preferredModelOutputFormat: preferredModelOutputFormat,
      // defaultMaxConvoTokens is part of AvailableModel, not BaseModelConfig directly
      defaultMaxConvoTokens: parseInt(defaultMaxConvoTokens, 10),
      // Fields from BaseModelConfig that might not be directly on the form but have defaults
      reservedOutputTokens: 0, // Example default
      systemPromptDisabled: false,
      roleParamsDisabled: false,
      stopDisabled: false,
      predictedOutputEnabled: false,
      reasoningEffortEnabled: false,
      reasoningEffort: "low",
      includeReasoning: false,
			supportsCacheControl: false,
      usesOpenAIResponsesAPI: false,
      singleMessageNoSystemPrompt: false,
      tokenEstimatePaddingPct: 0.0,
      modelCompatibility: { hasImageSupport: false },
    };


    // The backend expects modelId (the unique ID like 'gpt-4') in modelData.modelId
    // and modelName (user-friendly name) in modelData.modelName.
    // However, the shared.AvailableModel has Id (server-generated UUID) and BaseModelConfig.ModelId (e.g. 'gpt-4')
    // and BaseModelConfig.ModelName (e.g. 'GPT-4 display name')
    // For creation, the user provides their desired ModelId (e.g. 'my-custom-gpt') and ModelName.
    // The server will generate the UUID `Id`.

    // Let's adjust the payload based on shared.AvailableModel
     const payload = {
      // Id is generated by server, so not sent for POST
      baseModelConfig: {
        provider: provider,
        customProvider: provider === 'custom' ? modelName : null, // Example logic
        baseUrl: baseUrl,
        modelName: modelName, // User-defined display name for the model
        modelId: modelId,     // The actual model identifier string like 'gpt-4-turbo'
        maxTokens: parseInt(maxTokens, 10),
        maxOutputTokens: parseInt(maxOutputTokens, 10),
        reservedOutputTokens: 0,
        apiKeyEnvVar: apiKeyEnvVar,
        preferredModelOutputFormat: preferredModelOutputFormat,
        systemPromptDisabled: false,
        roleParamsDisabled: false,
        stopDisabled: false,
        predictedOutputEnabled: false,
        reasoningEffortEnabled: false,
        reasoningEffort: "low",
        includeReasoning: false,
        supportsCacheControl: false,
        usesOpenAIResponsesAPI: false,
        singleMessageNoSystemPrompt: false,
        tokenEstimatePaddingPct: 0.0,
        modelCompatibility: { hasImageSupport: false },
      },
      description: description,
      defaultMaxConvoTokens: parseInt(defaultMaxConvoTokens, 10),
      // CreatedAt and UpdatedAt are server-set
    };


    try {
      let response;
      if (isEditing && currentModel && currentModel.id) {
        // For PUT, we need to send the server-generated 'id' in the URL
        // and the full updated model structure in the body.
        // The payload for PUT should include the 'id' if the backend expects it for updates.
        // The current backend proxy for PUT uses `/custom_models/{modelId}` where modelId is the user-defined one.
        // Let's assume the backend expects the *user-defined modelId* in the path for now.
        const putPayload = { ...payload, id: currentModel.id, createdAt: currentModel.createdAt }; // Include ID and CreatedAt for update
        response = await fetch(`/api/ui/custom-models/${currentModel.modelId}`, { // currentModel.modelId is the user-defined one
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(putPayload),
        });
      } else {
        response = await fetch('/api/ui/custom-models', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload), // Send the refined payload
        });
      }

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`HTTP error! status: ${response.status}, message: ${errorText}`);
      }
      fetchCustomModels(); // Refresh list
      closeModal();
    } catch (error) {
      console.error("Failed to save custom model:", error);
      alert(`Error saving model: ${error.message}`);
    }
  }

  async function deleteModel(modelToDelete) {
    if (!confirm(`Are you sure you want to delete ${modelToDelete.modelName || modelToDelete.modelId}?`)) {
      return;
    }
    try {
      // The path for DELETE is /custom_models/{modelId} where modelId is the user-defined one.
      const idToDelete = modelToDelete.modelId; // User-defined modelId
      const response = await fetch(`/api/ui/custom-models/${idToDelete}`, {
        method: 'DELETE',
      });
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`HTTP error! status: ${response.status}, message: ${errorText}`);
      }
      fetchCustomModels(); // Refresh list
    } catch (error) {
      console.error("Failed to delete custom model:", error);
      alert(`Error deleting model: ${error.message}`);
    }
  }
</script>

<style>
  .container { padding: 20px; }
  .modal {
    position: fixed; top: 0; left: 0; width: 100%; height: 100%;
    background: rgba(0,0,0,0.5); display: flex;
    align-items: center; justify-content: center;
  }
  .modal-content { background: white; padding: 20px; border-radius: 5px; width: 500px; }
  .form-group { margin-bottom: 15px; }
  label { display: block; margin-bottom: 5px; }
  input, select, textarea { width: 100%; padding: 8px; box-sizing: border-box; }
  table { width: 100%; border-collapse: collapse; margin-top: 20px; }
  th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
  th { background-color: #f2f2f2; }
  .actions button { margin-right: 5px; }
  .error { color: red; margin-top: 5px; }
</style>

<div class="container">
  <h2>Custom Models</h2>
  <button on:click={openAddModal}>Add New Custom Model</button>

  {#if !customModels || customModels.length === 0}
    <p>No custom models found.</p>
  {:else}
    <table>
      <thead>
        <tr>
          <th>Model ID (User Defined)</th>
          <th>Display Name</th>
          <th>Provider</th>
          <th>Description</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {#each customModels as model}
          <tr>
            <td>{model.modelId}</td>
            <td>{model.modelName}</td>
            <td>{model.provider}</td>
            <td>{model.description}</td>
            <td class="actions">
              <button on:click={() => openEditModal(model)}>Edit</button>
              <button on:click={() => deleteModel(model)}>Delete</button>
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  {/if}

  {#if showModal}
    <div class="modal">
      <div class="modal-content">
        <h3>{isEditing ? 'Edit' : 'Add'} Custom Model</h3>
        <form on:submit|preventDefault={handleSubmit}>
          <div class="form-group">
            <label for="modelId">Model ID (e.g., gpt-4-turbo, claude-3-opus-20240229):</label>
            <input type="text" id="modelId" bind:value={modelId} required disabled={isEditing}>
            {#if isEditing}
              <small>Model ID cannot be changed after creation.</small>
            {/if}
          </div>
          <div class="form-group">
            <label for="modelName">Display Name (e.g., GPT-4 Turbo, Claude Opus):</label>
            <input type="text" id="modelName" bind:value={modelName} required>
          </div>
          <div class="form-group">
            <label for="description">Description:</label>
            <textarea id="description" bind:value={description}></textarea>
          </div>
          <div class="form-group">
            <label for="provider">Provider:</label>
            <select id="provider" bind:value={provider}>
              <option value="openai">OpenAI</option>
              <option value="anthropic">Anthropic</option>
              <option value="google">Google</option>
              <option value="custom">Custom (OpenRouter, etc.)</option>
            </select>
          </div>
           <div class="form-group">
            <label for="baseUrl">Base URL (optional, for custom providers):</label>
            <input type="text" id="baseUrl" bind:value={baseUrl}>
          </div>
          <div class="form-group">
            <label for="apiKeyEnvVar">API Key Environment Variable (e.g., OPENAI_API_KEY):</label>
            <input type="text" id="apiKeyEnvVar" bind:value={apiKeyEnvVar} required>
          </div>
          <div class="form-group">
            <label for="maxTokens">Max Tokens (Context Window):</label>
            <input type="number" id="maxTokens" bind:value={maxTokens}>
          </div>
           <div class="form-group">
            <label for="maxOutputTokens">Max Output Tokens:</label>
            <input type="number" id="maxOutputTokens" bind:value={maxOutputTokens}>
          </div>
          <div class="form-group">
            <label for="defaultMaxConvoTokens">Default Max Conversation Tokens (for Planner):</label>
            <input type="number" id="defaultMaxConvoTokens" bind:value={defaultMaxConvoTokens}>
          </div>
          <div class="form-group">
            <label for="preferredModelOutputFormat">Preferred Output Format:</label>
            <select id="preferredModelOutputFormat" bind:value={preferredModelOutputFormat}>
              <option value="xml">XML</option>
              <option value="tool-call-json">Tool Call JSON</option>
            </select>
          </div>
          <button type="submit">{isEditing ? 'Save Changes' : 'Create Model'}</button>
          <button type="button" on:click={closeModal}>Cancel</button>
        </form>
      </div>
    </div>
  {/if}
</div>
